# Generated by Django 4.0.3 on 2022-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
